### PR TITLE
Add a database to run tests against it

### PR DESCRIPTION
**Pull request by vitormsilva**
Add the catalgue-database only for testing..

The point is have on docker-hub a database like https://hub.docker.com/r/rethink/catalogue-database-rethinkdefault/ but for testing, like `/catalogue-database-testing`

### CODE REVIEW

**Comment by emmelmann-fokus** [comment]
Just prepare the corresponding files / directory strcutre in the repo and ping me.  I can add then the additional docker image on docker hub.

**Comment by vitormsilva** [comment]
Thank you @emmelmann-fokus,

I added here, on this pull request:

https://github.com/reTHINK-project/dev-catalogue/tree/testing-catalogue-database/docker/catalogue-database-tests

I don't know if it this what you want..

**Comment by emmelmann-fokus** [comment]
ok.  @Endebert please review and approve; i will then add the entries in docker hub.

**Comment by vitormsilva** [comment]
@emmelmann-fokus 

The build was failing could you see what happening?
https://hub.docker.com/r/rethink/catalogue-test-client/builds/

Thank you

**Comment by emmelmann-fokus** [comment]
Sure, here is the copy of the error message:

```
Building in Docker Cloud's infrastructure...
Starting to clone
Cloning into '.'...

Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Cloning done
Build path does not exist: ./docker/catalogue-test-client
```

It was run on the "dev" branch.

**Comment by vitormsilva** [comment]
But the path is wrong..

I mention the name for the database, `catalogue-database-tests`, [here](https://github.com/reTHINK-project/dev-catalogue/pull/52#issuecomment-257853553) but the build path is pointing for an path does not exits: `./docker/catalogue-test-client`. 

Shouldn't be `./docker/catalogue-database-tests`?

**Comment by emmelmann-fokus** [comment]
Yes, you are completely right.

I used to have the same name for the directory as I used for the name of the docker hub file.  I guess I was stuck in that pattern and used the wrong path name.

I just updated it and the build for the dev branch worked.
Once the dev branch is merged into the master, the "latest" build of the docker image should also pass.

**Comment by vitormsilva** [comment]
Ok.. Thank you..

**Comment by emmelmann-fokus** [comment]
@vitormsilva the testing-catalogue-d... branch was merged.  Should we delete it or keep it for further activities?

In either case, can we close this issue (since we fixed the docker hub issue) or are there additional open issues arising from this thread.

**Comment by vitormsilva** [comment]
We should delete it.. you delete it, or you want I do that?
But this isn't an issue only the pull request :)

**Comment by emmelmann-fokus** [comment]
Just done.  And closing this issue.  Just reopen if we need to iterate.

Thanks,

**Pull request merged**
